modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="justifylasers"
version="${version}"
displayName="JustifyLasers"
authors="Mr.Askick"
logoFile="assets/justifylasers/icon.png"
description="Laser emitters, receivers, portable refocusing cubes, and optional energy-powered lasers."

[[mixins]]
config="justifylasers.client.mixins.json"

[[mixins]]
config="justifylasers.mixins.json"

[[dependencies.justifylasers]]
modId="neoforge"
type="required"
versionRange="[21.1.200,)"
ordering="NONE"
side="BOTH"

[[dependencies.justifylasers]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
