plugins {
    id 'base'
    id 'dev.architectury.loom' version '1.11.458' apply false
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group
}

tasks.register('collectJars', Copy) {
    subprojects.each { target ->
        dependsOn "${target.path}:remapJar"
        from(target.layout.buildDirectory.dir('libs')) {
            include "JustifyLasers-${target.name}-${project.version}.jar"
        }
    }
    into layout.buildDirectory.dir('libs')
}

tasks.named('build') {
    dependsOn subprojects.collect { "${it.path}:build" }
    dependsOn 'collectJars'
}

['test', 'runGameTest', 'runClient', 'runServer'].each { taskName ->
    tasks.register(taskName) { dependsOn ":fabric-1.20.1:${taskName}" }
}
